#!/bin/sh
VERSION='v8.1.2'
# ---------------------- BUILD
docker build --build-arg BRANCH=${VERSION} --no-cache --tag grafana:build .

# ---------------------- TEST

# ---------------------- DEPLOY
docker tag grafana:build gautada/grafana:${VERSION}
docker push gautada/grafana:${VERSION}
